### ISSUE TITLE
Improve text display in METexpress

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#104]
Now that METexpress is capable of plotting both summary and aggregate statistics, we should update the text stat display to take advantage of this fact. If someone wants the overall statistic, they should be able to see the components that went into in, while if someone wants the mean or median statistic, they should get that value plus standard deviation, N, etc.

**Comment by bonnystrong** [comment]
Molly wants to get this into METplus 5.0.0 by Dec 15.  Current version not giving users a very good experience.

**Comment by bikegeek** [comment]
RC 1 is planned for December 1, can you get it done by then?


---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by mollybsmith-noaa** [comment]
This is actually a METexpress-only issue, so it shouldn’t get in the way of
the other METplus components. Sorry for the confusion. Is that okay?

**Comment by bikegeek** [comment]
Yes, thanks for the clarification !
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by mollybsmith-noaa** [comment]
The text display in METexpress works well for all plot types now.
