### ISSUE TITLE
Update met-cyclone app to support new RI CTC statistics

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#130]
## Describe the New Feature ##
*The upcoming MET 11.1.0 release creates contingency table statistics for TC rapid intensification that can be stored in the existing METplus MySQL database (thanks MET team!). The met-cyclone app now needs to be updated to support these statistics.*

### Acceptance Testing ###
*Automated tests should pass while plotting new RI CTC plots.*

### Time Estimate ###
*3-5 business days.*

### Relevant Deadlines ###
*HFIP season is upon us so this should be done as quickly as possible.*

**Comment by bonnystrong** [comment]
Molly will email Shan to see if they need it this year.

**Comment by mollybsmith-noaa** [comment]
I'll add this in with the slate of METexpress updates I'm currently doing.

**Comment by mollybsmith-noaa** [comment]
This is fully done now.
