### ISSUE TITLE
Investigate METexpress AWS VM failure

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#39]
Our AWS VM crashed for the second time in six months on Monday, to the point where it was not even possible to ssh in with a terminal window. Barbara Manteaw suspects that it is because our docker containers rapidly fill up their /var/lib/docker partitions, but I am not sure this is the case. It is true that they fill up a lot of space at the start, because the AWS metadata is so gigantic, but then they should not store much at all, and any cached plot specs should expire after 8 hours. The docker partitions were at 87% capacity when the apps started up yesterday morning, 87% last night, and 87% this morning, so there is definitely not dramatic growth going on. If we want to add more apps later we will likely need more space, but for now, this seems sufficient. Regardless, we should investigate the cause of the crash.

The full text of Barbara's email:

"""Hello All,

So the docker images - overlays appears to be consuming so much disk space and then at a point it causes the ec2 instance to either stop or become unresponsive, so developers must get scripts to consistently prune those docker images or risk the instability of the system with the current space, so obviously there is the need for expansion of disk and pruning; else, expansion will still be filled up with these docker images that keep increasing by the day. Below is the filesystem as seen on MetExpress as at yesterday evening (4:50 EST). Let us know your plans as we do the migration, thanks.

[root@ip-205-156-8-94 overlay2]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.6G     0  7.6G   0% /dev
tmpfs           7.6G     0  7.6G   0% /dev/shm
tmpfs           7.6G   50M  7.5G   1% /run
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/nvme0n1p1   20G   18G  2.7G  87% /
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/f6f28f986d3b07c41b3d40c3a6cbb05fcba006a9593c08e60d4b4987d2b1e2f8/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/b09e8a0f35e54a66ab7ee1d8acb646aee8463b26e374aae9c0acb3ad1cb9c6c4/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/e6b075e51319365ecfc5df3a148ee6c3f1f9a926c47df858322530c4187ed0a4/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/3eb792a34e8dac5f7a2bd0a3cb12fae7cafc705f9433b5839e9329834fdef3fa/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/5d1ab681be765fca5af85fc7a2259a779ffc098a753e70fd1af0ee132c564e5b/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/b77096badc1bf16535a55bd18a2083416dd2ebffa743c57299d7992bceaa28f8/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/c87dd149ffa07aff07660aad041d1ff662513545150ed5df3bfc6f0bffc902b4/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/cf113b685c9b4d998bba615fe5d3561cd3e8f833b8d1ec26ddb2a970f39d0ea2/merged
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/41f1759570d9d5b52e12a4401b318b9b091681097c74332ec6bdab150a68f485/merged
shm              64M     0   64M   0% /var/lib/docker/containers/537b3a4e53009a348b5fdf0f5f73f5375a94b40f86cf1cd11cc9ab7f8743b8e4/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/43e8a9b28e5d52ab9fea5c94d72973aa39042b3a9aef505a1a36273679c46324/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/f4deb5a18028e6b4f7fb7aa98bfeb75fef80f1a38b34b9b360fe888edc415a09/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/ef04a7c0087c793405c40bf2b312fb5a4f276b66ac50acef386c51c7ba089afb/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/a867da78e1c69d53c380b8f0391eea51ee2486c3fdd8d7179fe19594088e51f6/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/d9d6bccd858342420897d1af65fbc97537535265ba1e36082d606dc2524005d5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/7da8f8dfdee61a9ffb92bf8d2d0ff17c086627dec379edac05f424a2092a28ef/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/2e2ec8da70b9ca5be991f36bac946901306fbede18fcad56ff53145ff437a42b/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/c8717475052001fb8e04aa42e3560d96f3ff9cece36ba9378ed67851b76a0995/mounts/shm
overlay          20G   18G  2.7G  87% /var/lib/docker/overlay2/efda31f97b61ccd59109d87075329ac83e31a2b6eea14787cdb1357c781aaba7/merged
shm              64M     0   64M   0% /var/lib/docker/containers/54026ec3e1416db6863e55c106efb3f2e52e7cfc3690bd381e564e42796a9f59/mounts/shm
tmpfs           1.6G     0  1.6G   0% /run/user/0
[root@ip-205-156-8-94 overlay2]# du -sh
11G     ."""

Randy's reply (and yes, we do purge old containers at each update, so that is not what is causing this problem):

"""There needs to be one overlay for each current running container. Unfortunately docker doesn't automatically remove the old image overlays so when we install a new image sometimes the old image is accidentally retained. We can remove unused image overlays with a "docker system prune -a -f" and we usually do this as a rule of thumb when we update the images.

We will look into making sure this is incorporated into our update process. Maybe we can automate it.

I suspect this is the root of the problem.

Molly and I will figure it out.

Of course it is a different issue if there isn't enough disk space to accommodate the 8 to 10 images that we need to run, but I think we have enough disk space if it is managed better.
randy"""

**Comment by randytpierce** [comment]
We now believe that this was due to a disk space issue and have since upgraded the disk space on the VM (and the new VM). Since we haven't seen any further problems with this since the upgrade nearly. a month ago I am closing this issue.
