### ISSUE TITLE
Add non-pair statistics to MET Objects

### ISSUE THREAD

**Issue by mollybsmith-noaa** [dtcenter/METexpress#92]
John HG has said that, in his experience, people using the METplus MODE tool like to verify non-pair attributes, in addition to paired ones. METexpress currently only plots paired statistics, but we should add in the non-pair ones too.

**Comment by mollybsmith-noaa** [comment]
Part of the METcalcpy effort for METexpress.

**Comment by bonnystrong** [comment]
We need to look at why this Medium priority is in the ToDo status while High priority items remain in the BackLog.

**Comment by mollybsmith-noaa** [comment]
It will happen as a side effect of the METcalcpy work. I think it says so
I’m the comments? If not I’ll add that.

**Comment by mollybsmith-noaa** [comment]
The METexpress MODE app now has all the 2d single-object statistics that METviewer does.
